// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDueLKVAmvjPVt6HNsRkOtxyGMGn38FNfA',
    appId: '1:1098980746551:android:bad6e2035fe2374811e6b2',
    messagingSenderId: '1098980746551',
    projectId: 'vehicle-explorer',
    databaseURL: 'https://vehicle-explorer-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vehicle-explorer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7dUPR2unjE9eF_EnUW22X7G4PHvkiYSI',
    appId: '1:1098980746551:ios:6383ac3e9e6bf8ca11e6b2',
    messagingSenderId: '1098980746551',
    projectId: 'vehicle-explorer',
    databaseURL: 'https://vehicle-explorer-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vehicle-explorer.appspot.com',
    iosBundleId: 'com.example.coolapp',
  );
}
